# basic script to run apache2 
FROM ubuntu 
RUN apt-get update 
RUN apt-get install -y apache2 
RUN apt-get install -y apache2-utils 
RUN apt-get clean 
EXPOSE 80 CMD ["apache2ctl", "-D", "FOREGROUND"]

#node js
FROM ubuntu
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN apt-get clean 
